name: Docker Image CI

on:
  push:
    branches: [ "develop" ]

env:
  spark_version: 3.4.1
  java_version: 8
  sbt_version: 1.9.6
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Spark Docker image
        run: |
          docker build \
          --build-arg "SPARK_VERSION=$spark_version" \
          --build-arg "JAVA_VERSION=$java_version" \
          --build-arg "SBT_VERSION=$sbt_version" \
          --tag osekoo/spark:$spark_version \
          .
