name: Docker Image CI

on:
  push:
    branches: [ "develop" ]

env:
  spark_version: 3.5.0
  java_version: 17
  sbt_version: 1.9.7
  registry: ghcr.io
  image_tag: osekoo/spark:${{ env.spark_version }}

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Spark Docker image
        run: |
          docker build \
          --build-arg "SPARK_VERSION=${{ env.spark_version }}" \
          --build-arg "JAVA_VERSION=${ {env.java_version }}" \
          --build-arg "SBT_VERSION=${ {env.sbt_version}}" \
          --tag ${{ env.image_tag }} \
          .
          docker push ${{ env.image_tag }}